### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by arvind** [vega/typescript-to-json-schema#2]
When I try to run `typescript-to-json-schema` against the `Legend` union type [defined here](https://github.com/vega/vega-parser/blob/as/typings/typings/legend.ts), I get a `Maximum call stack size exceeded` error. Each individual type within the union builds just fine, however. 

Is there something about my type definitions I should be modifying/simplifying, or is this a bug with `typescript-to-json-schema`?

```
$ ./node_modules/.bin/typescript-to-json-schema --path typings/legend.ts --type Legend
/Users/arvind/Research/vega3/vega-parser/node_modules/typescript-to-json-schema/dist/typescript-to-json-schema.js:32
        throw error;
        ^

RangeError: Maximum call stack size exceeded
    at CircularReferenceTypeFormatter.getChildren (/Users/arvind/Research/vega3/vega-parser/node_modules/typescript-to-json-schema/dist/src/CircularReferenceTypeFormatter.js:26:23)
...
```

```
$ ./node_modules/.bin/typescript-to-json-schema --path typings/legend.ts --type SizeLegend
(executes correctly)
```

**Comment by arvind** [comment]
Interestingly, if I switch the interfaces to type aliases, I've found:

* The same error if each individual legend is an intersection with base legend:
  ```typescript
  export type SizeLegend = BaseLegend & {size: string};
  ...
  export type Legend = SizeLegend | ShapeLegend | ...
  ```
* However, no error if the intersection occurs on `Legend`:
  ```typescript
  export type SizeLegend = {size: string};
  ...
  export type Legend = BaseLegend & (SizeLegend | ShapeLegend | ...);
  ```
While the latter is legal, the former (or the interface formulation currently checked in) provides more useful exported types.

**Comment by domoritz** [comment]
As with https://github.com/vega/typescript-to-json-schema/issues/4, I suspect this is because of the version on NPM. I don't get this error.

**Comment by domoritz** [comment]
Seeing the same issue when I use the full typings.

**Comment by domoritz** [comment]
The problem seems to be that we actually need a larger stack. 

```
node --stack-size=100000 dist/typescript-to-json-schema.js --path /Users/domoritz/Developer/UW/vega-parser/typings/legend.ts --type Legend
```

Works fine.

**Comment by domoritz** [comment]
After looking at this in more depth, I can't think of a fix that does not involve some non-trivial rewrite of the formatting logic. Please increase the stack size.
