### ISSUE TITLE
How to use existing tsconfig?

### ISSUE THREAD

**Issue by marvinhagemeister** [vega/typescript-to-json-schema#6]
Just gave the project ago, but I'm seeing lots of errors like these:

```bash
/myproject/node_modules/@types/node/index.d.ts(390,48): error TS2304: Cannot find name 'Promise'.
/myproject/node_modules/@types/node/index.d.ts(392,62): error TS2304: Cannot find name 'Promise'.
/myproject/node_modules/@types/node/index.d.ts(505,50): error TS2304: Cannot find name 'Promise'.
/myproject/node_modules/@types/node/index.d.ts(507,65): error TS2304: Cannot find name 'Promise'.
```

Is there a way to override the included typescript `libs`definitions, or even better reuse the existing `tsconfig.json`?

**Comment by domoritz** [comment]
I think it should work. See https://github.com/vega/typescript-to-json-schema/blob/master/factory/program.ts#L9. Please reopen if it doesn't.

**Comment by marvinhagemeister** [comment]
That's awesome. I was trying to generate the schemas via the cli and didn't find the relevant option. I'll try the programmatic way of creating them.

**Comment by domoritz** [comment]
Hmm, reading the code I think you can just pass the path to the tsconfig file on the cli. I don't think you have to use the programmatic way.
